// <auto-generated />
using CodeFirstApproach.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstApproach.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstApproach.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Age = 1,
                            Department = "IT",
                            EmployeeName = "Employee1",
                            Salary = 200.0
                        },
                        new
                        {
                            EmployeeID = 2,
                            Age = 2,
                            Department = "HR",
                            EmployeeName = "Employee2",
                            Salary = 1000.0
                        },
                        new
                        {
                            EmployeeID = 3,
                            Age = 3,
                            Department = "IT",
                            EmployeeName = "Employee3",
                            Salary = 600.0
                        },
                        new
                        {
                            EmployeeID = 4,
                            Age = 4,
                            Department = "HR",
                            EmployeeName = "Employee4",
                            Salary = 2000.0
                        },
                        new
                        {
                            EmployeeID = 5,
                            Age = 5,
                            Department = "IT",
                            EmployeeName = "Employee5",
                            Salary = 1000.0
                        },
                        new
                        {
                            EmployeeID = 6,
                            Age = 6,
                            Department = "HR",
                            EmployeeName = "Employee6",
                            Salary = 3000.0
                        },
                        new
                        {
                            EmployeeID = 7,
                            Age = 7,
                            Department = "IT",
                            EmployeeName = "Employee7",
                            Salary = 1400.0
                        },
                        new
                        {
                            EmployeeID = 8,
                            Age = 8,
                            Department = "HR",
                            EmployeeName = "Employee8",
                            Salary = 4000.0
                        },
                        new
                        {
                            EmployeeID = 9,
                            Age = 9,
                            Department = "IT",
                            EmployeeName = "Employee9",
                            Salary = 1800.0
                        },
                        new
                        {
                            EmployeeID = 10,
                            Age = 10,
                            Department = "HR",
                            EmployeeName = "Employee10",
                            Salary = 5000.0
                        },
                        new
                        {
                            EmployeeID = 11,
                            Age = 11,
                            Department = "IT",
                            EmployeeName = "Employee11",
                            Salary = 2200.0
                        },
                        new
                        {
                            EmployeeID = 12,
                            Age = 12,
                            Department = "HR",
                            EmployeeName = "Employee12",
                            Salary = 6000.0
                        },
                        new
                        {
                            EmployeeID = 13,
                            Age = 13,
                            Department = "IT",
                            EmployeeName = "Employee13",
                            Salary = 2600.0
                        },
                        new
                        {
                            EmployeeID = 14,
                            Age = 14,
                            Department = "HR",
                            EmployeeName = "Employee14",
                            Salary = 7000.0
                        },
                        new
                        {
                            EmployeeID = 15,
                            Age = 15,
                            Department = "IT",
                            EmployeeName = "Employee15",
                            Salary = 3000.0
                        },
                        new
                        {
                            EmployeeID = 16,
                            Age = 16,
                            Department = "HR",
                            EmployeeName = "Employee16",
                            Salary = 8000.0
                        },
                        new
                        {
                            EmployeeID = 17,
                            Age = 17,
                            Department = "IT",
                            EmployeeName = "Employee17",
                            Salary = 3400.0
                        },
                        new
                        {
                            EmployeeID = 18,
                            Age = 18,
                            Department = "HR",
                            EmployeeName = "Employee18",
                            Salary = 9000.0
                        },
                        new
                        {
                            EmployeeID = 19,
                            Age = 19,
                            Department = "IT",
                            EmployeeName = "Employee19",
                            Salary = 3800.0
                        },
                        new
                        {
                            EmployeeID = 20,
                            Age = 20,
                            Department = "HR",
                            EmployeeName = "Employee20",
                            Salary = 10000.0
                        },
                        new
                        {
                            EmployeeID = 21,
                            Age = 21,
                            Department = "IT",
                            EmployeeName = "Employee21",
                            Salary = 4200.0
                        },
                        new
                        {
                            EmployeeID = 22,
                            Age = 22,
                            Department = "HR",
                            EmployeeName = "Employee22",
                            Salary = 11000.0
                        },
                        new
                        {
                            EmployeeID = 23,
                            Age = 23,
                            Department = "IT",
                            EmployeeName = "Employee23",
                            Salary = 4600.0
                        },
                        new
                        {
                            EmployeeID = 24,
                            Age = 24,
                            Department = "HR",
                            EmployeeName = "Employee24",
                            Salary = 12000.0
                        },
                        new
                        {
                            EmployeeID = 25,
                            Age = 25,
                            Department = "IT",
                            EmployeeName = "Employee25",
                            Salary = 5000.0
                        },
                        new
                        {
                            EmployeeID = 26,
                            Age = 26,
                            Department = "HR",
                            EmployeeName = "Employee26",
                            Salary = 13000.0
                        },
                        new
                        {
                            EmployeeID = 27,
                            Age = 27,
                            Department = "IT",
                            EmployeeName = "Employee27",
                            Salary = 5400.0
                        },
                        new
                        {
                            EmployeeID = 28,
                            Age = 28,
                            Department = "HR",
                            EmployeeName = "Employee28",
                            Salary = 14000.0
                        },
                        new
                        {
                            EmployeeID = 29,
                            Age = 29,
                            Department = "IT",
                            EmployeeName = "Employee29",
                            Salary = 5800.0
                        },
                        new
                        {
                            EmployeeID = 30,
                            Age = 30,
                            Department = "HR",
                            EmployeeName = "Employee30",
                            Salary = 15000.0
                        },
                        new
                        {
                            EmployeeID = 31,
                            Age = 31,
                            Department = "IT",
                            EmployeeName = "Employee31",
                            Salary = 6200.0
                        },
                        new
                        {
                            EmployeeID = 32,
                            Age = 32,
                            Department = "HR",
                            EmployeeName = "Employee32",
                            Salary = 16000.0
                        },
                        new
                        {
                            EmployeeID = 33,
                            Age = 33,
                            Department = "IT",
                            EmployeeName = "Employee33",
                            Salary = 6600.0
                        },
                        new
                        {
                            EmployeeID = 34,
                            Age = 34,
                            Department = "HR",
                            EmployeeName = "Employee34",
                            Salary = 17000.0
                        },
                        new
                        {
                            EmployeeID = 35,
                            Age = 35,
                            Department = "IT",
                            EmployeeName = "Employee35",
                            Salary = 7000.0
                        },
                        new
                        {
                            EmployeeID = 36,
                            Age = 36,
                            Department = "HR",
                            EmployeeName = "Employee36",
                            Salary = 18000.0
                        },
                        new
                        {
                            EmployeeID = 37,
                            Age = 37,
                            Department = "IT",
                            EmployeeName = "Employee37",
                            Salary = 7400.0
                        },
                        new
                        {
                            EmployeeID = 38,
                            Age = 38,
                            Department = "HR",
                            EmployeeName = "Employee38",
                            Salary = 19000.0
                        },
                        new
                        {
                            EmployeeID = 39,
                            Age = 39,
                            Department = "IT",
                            EmployeeName = "Employee39",
                            Salary = 7800.0
                        },
                        new
                        {
                            EmployeeID = 40,
                            Age = 40,
                            Department = "HR",
                            EmployeeName = "Employee40",
                            Salary = 20000.0
                        },
                        new
                        {
                            EmployeeID = 41,
                            Age = 41,
                            Department = "IT",
                            EmployeeName = "Employee41",
                            Salary = 8200.0
                        },
                        new
                        {
                            EmployeeID = 42,
                            Age = 42,
                            Department = "HR",
                            EmployeeName = "Employee42",
                            Salary = 21000.0
                        },
                        new
                        {
                            EmployeeID = 43,
                            Age = 43,
                            Department = "IT",
                            EmployeeName = "Employee43",
                            Salary = 8600.0
                        },
                        new
                        {
                            EmployeeID = 44,
                            Age = 44,
                            Department = "HR",
                            EmployeeName = "Employee44",
                            Salary = 22000.0
                        },
                        new
                        {
                            EmployeeID = 45,
                            Age = 45,
                            Department = "IT",
                            EmployeeName = "Employee45",
                            Salary = 9000.0
                        },
                        new
                        {
                            EmployeeID = 46,
                            Age = 46,
                            Department = "HR",
                            EmployeeName = "Employee46",
                            Salary = 23000.0
                        },
                        new
                        {
                            EmployeeID = 47,
                            Age = 47,
                            Department = "IT",
                            EmployeeName = "Employee47",
                            Salary = 9400.0
                        },
                        new
                        {
                            EmployeeID = 48,
                            Age = 48,
                            Department = "HR",
                            EmployeeName = "Employee48",
                            Salary = 24000.0
                        },
                        new
                        {
                            EmployeeID = 49,
                            Age = 49,
                            Department = "IT",
                            EmployeeName = "Employee49",
                            Salary = 9800.0
                        },
                        new
                        {
                            EmployeeID = 50,
                            Age = 50,
                            Department = "HR",
                            EmployeeName = "Employee50",
                            Salary = 25000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
